package com.mohamed.barki.asl.lite.resactivity;

import android.app.Activity;
public class ResActivityR extends Activity
{
	public static String[][] resList = new String[][]{
			//المستشفى
			{"r0", "166ljyG_3wgB5TnACgKKVyOni0jEDRTSX", "premiers secours", "إسعافات أولية"},
			{"r1", "url", "analyse médicales1", "تحاليل طبية1"},
			{"r2", "url", "tensiomètre", "جهاز قياس ضغط الدم"},
			{"r3", "url", "suppositoire", "لبوس، تحميلة"},
			{"r4", "1677zA68z-FcmfrH6XxkA46iMCJPWtPTd", "sparadrap", "ضمادات لاصقة"},
			{"r5", "1iWde7D6BpyOPhb0q59BJrtvRVZFpnPOJ", "bandage", "ضمادة"},
			{"r6", "169KgmWxWrtP4ojHpCBKcJUqg2_cK-EbJ", "vaccination1", "تلقيح1"},
			{"r7", "16EzrEfGZ5Sy_yGQbGIk-OYGfElTlrbi9", "guérison", "شفاء"},
			{"r8", "16IqStNQ6kVHDCnnxXdiz6yyu_ESoBsmP", "traitement", "علاج"},
			{"r9", "16K4-ihAwuADcR3DBwaXDmRFEYiFuHiYg", "scanner médical", "ماسح ضوئي طبي"},
			{"r10", "16MubkY1VN827sdFIItGsnVPr1j92M_eu", "santé", "صحة"},
			{"r11", "16O4XvhVZ4QUEhgFa-wLk4SCLIWZbLUPS", "tension artérielle", "ضغط دموي"},
			{"r12", "16Oonn4jca_n3myXh4-TpfKPYWozT_9tt", "médecin", "طبيب"},
			{"r13", "url", "vaccination2", "تلقيح2"},
			{"r14", "16Se2PZBGHXXD7t2d-EQOxIAkrLLdF4t5", "injection", "حقنة"},
			{"r15", "16UyPsLrR8VzbSVw_9B5rsZnl2x-oyDhe", "médicament", "دواء"},
			{"r16", "16YUs8BDtnGhOqsJTmSIVFD1Z2R7e7GKV", "radiologie médicale", "أشعة طبية"},
			{"r17", "16cd3-OtY0CFg4EdKZzzENG_jrPaTee_e", "comprimé", "قرص دواء"},
			{"r18", "16hSMCGZXrE3jvt51VB-hlmLEK-nuhCzR", "douleur", "ألم"},
			{"r19", "16mi7Ggad05fEhluOMqZn37p60smFdBzH", "seringue", "إبرة الحقن"},
			{"r20", "16oEgDHLraiDwqga1-ZGrnuiHjlEf4zC9", "ortophoniste", "أخصائي أورطوفوني"},
			{"r21", "url", "compte-gouttes", "قطارة الدواء"},
			{"r22", "16pNw7PYU2w794RD63Brvvkda2VxDVXV5", "diabète", "داء السكري"},
			{"r23", "16rqK0RRQhcV2_QHaCezXLgg_uG9jRl3Z", "analyses médicales2", "تحاليل طبية2"},
			{"r24", "16xrmRNNUG-dBC5rIV8r5go79wodKaC3l", "maladie", "مرض"},
			{"r25", "176iIQChCLikGowu6XnnhQY_QP5JXGiWt", "psychiatre", "طبيب الأمراض العقلية"},
			{"r26", "17CTVKqyMfbiaa4g-e-UFQIY6vFfQOs_j", "chirurgien dentiste", "جراح الأسنان"},
			{"r27", "17Ct8HGqwnImllkavGgbqRTQ238EPKpp2", "sirop", "شراب صيدلاني"},
			{"r28", "17D1iHz6sX93axOYhu1ltqEKKLzzyidUB", "chirurgien", "طبيب جراح"},
			{"r29", "17F7QjmXTuSClP8RyWpnBHH_XDcxnjPMk", "cardiologue", "طبيب القلب"},
			{"r30", "17FpxLbEAI1OtPxlOBDU3AJU281eHq6qW", "ophtalmologue", "طبيب العيون"},
			{"r31", "17H8Z-zR7llsGnyvQMDbev92LI75hkVGG", "pommade", "مرهم"},
			{"r32", "17JkUgF94ItyD9XXYQr4BiXwLl6i-M8fF", "opération chirurgicale", "عملية جراحية"},
			{"r33", "17OzBJmXv73XRXl6sJUKhmA9Slv-7nGi7", "psychologue", "طبيب نفساني"},
			{"r34", "17TR-x_k50g5WCP8NBJ2gqvUIVbugBJyL", "infirmier", "ممرض"},
			{"r35", "17VAaKzMFr9fdbVX_5Q2UOKl7CiS8g-OT", "dossier médical", "ملف طبي"},
			{"r36", "17VVi3xyQ9LBXTbgxbnIWLo1OQc3OsIiF", "hôpital2", "مستشفى2"},
			{"r37", "17VfZ5BwkgFN9Tz_nTgcxg5CvNBIHxS0p", "échographie", "تخطيط الصدى (ماسح صوتي)"},
			{"r38", "13vhAxuPTa5GZzH4AjmZb--_ArzcMKR0i", "pharmacien1", "صيدلي1"},
			{"r39", "17c5Mi6xJ5hT2lyZzRjv-kvjp_CvqkQKd", "ordonnance médicale", "وصفة طبية"},
			{"r40", "17l5OBwBy2kblWXYnggOLF_xkx79WNRYC", "thermomètre médical", "محرار طبي"},
			{"r41", "url", "ampoule buvable", "أنبوبة للشرب"},
			{"r42", "1iWu32dijL5puHxBbINWbh9ogyOHlG-MD", "dentiste", "طبيب الأسنان"},
			{"r43", "13xKeuQUxgSan4cUqEg8_arjuSxCuiiK4", "pharmacien2", "صيدلي2"},
			{"r44", "url", "orthophoniste", "معالج النطق"},
			{"r45", "url", "oto-rhino-laryngologiste ORL", "أخصائي أنف وأذن وحنجرة"},
			{"r46", "url", "accompagnement d'un étudiant handicapé AESH", "مرافق طالب معاق"},
			{"r47", "url", "audioprothésiste", "أخصائي تقويم السمع"},
			{"r48", "url", "psychomotricien", "المعالج النفسي"},
			{"r49", "url", "intermédiateur", "وسيط"},
			{"r50", "url", "professeur spécialisé", "أستاذ متخصص"},
	};
}
