package com.mohamed.barki.asl.lite.resactivity;

import android.app.Activity;
public class ResActivityW extends Activity
{
	public static String[][] resList = new String[][]{
			//الدين
			{"w0", "1Z7rt6hox5BZSA6fHEYshN-iLyZmG4HZf", "allah, dieu", "اللَّه"},
			{"w1", "1ZBnHzzMlmhY0xL-J4RFU4c4QXP6N6clc", "zakate", "زكاة"},
			{"w2", "1ZEO31yo602bZ_LQayHify-GT3uuRNfmI", "sunna nabawia1", "السُنَّة النبوية1"},
			{"w3", "1ZEYw3tO67fLlMUruCySYrMr7jpIfa1VS", "mauvaise action", "سيئة"},
			{"w4", "1ZF5dnh3E0h7te6LTYIPXZGaEpYya06XR", "polythéisme", "شرك بالله"},
			{"w5", "1ZNg6Owx3srK32EzI0KMyl3D3gP74Djt7", "sa'y", "سعي"},
			{"w6", "1ZOEFK9L9Fz17SrGgZs0YhBy9cLUSgsG6", "halal", "حلال"},
			{"w7", "1ZPNniq6r_Zte14kf3vs6iQSvdxpUvSQy", "la foi1", "الإيمان1"},
			{"w8", "url", "sunna nabawia2", "السُنَّة النبوية2"},
			{"w9", "1ZTTMwoUukFYTXNI9VIukucPTA2jZj_Vq", "repentance", "توبة"},
			{"w10", "1ZfJHzcjU_UPtZl9Y55nlGY37QgJpRdva", "croire en dieu", "الإيمان بالله"},
			{"w11", "1ZiBZn27qppBNsNHAxTwXsDPsj7SRRFaF", "pilliers de la foi1", "أركان الإيمان1"},
			{"w12", "1Zn-s0P_QxkrdDiRhU_AbnTr2F_ahZlVA", "islam", "الإسلام"},
			{"w13", "1Zu3cH1keK5JF0YF7I-xjGHxtaW0x_tUb", "habit de pèlerinage", "إحرام"},
			{"w14", "1Zz9ETRqmBuIOR25OHMGn7CtpvHMhCfbe", "croire au jour du jugement dernier", "الإيمان باليوم الآخر"},
			{"w15", "1_5uuWMw7Kseksey_n-b5TphGQDRBcyR8", "pilliers de l'islam", "أركان الإسلام"},
			{"w16", "1_6a5tpOhiAruckiWfM81Yq61coPIVcRX", "haram, péché", "حرام"},
			{"w17", "1_B4CKWu3nrGTqFvk8eqAGA_rj_1d9iT2", "croire aux prophètes1", "الإيمان بالرسل1"},
			{"w18", "1_GrJPJzUXpxjFs7nTA8uu3uAqmSJ4ll7", "religions", "التربية الدينية، الدين، الأديان"},
			{"w19", "1_HmwY1kJvXfSdqMrMqTFGKvgMs324ktK", "prophète", "الرسول"},
			{"w20", "1_MhBR5TOoIv0tLNu-GdqYZ0ggP8aJ5JW", "boudhisme", "بوذية"},
			{"w21", "1_NYTvWDkIRNGlmABsJbofaHoCzQk3_Q6", "châtiment divin", "الحساب الإلهي"},
			{"w22", "1_QagF3QsmqUaxQPAViCuPJfDhk_Ind2B", "unicité d'Allah", "توحيد"},
			{"w23", "1__6jl5q0EAuZn8rriqlbS1ZJqRV8xA9H", "hadj, pèlerinage", "حج"},
			{"w24", "1_al8P_8IXKfeOjGpHWrieXpa6zXcisOI", "paradis", "جنة"},
			{"w25", "1_jmUsyPZssrR-kOYYKJr48ZEg7B4Sgu3", "croire aux livres monothéistes1", "الإيمان بالكتب السماوية1"},
			{"w26", "1_mc9v8QK3Jh4CbisLCgibd5eAlSLdyOE", "bonne action", "حسنة"},
			{"w27", "1_qXTXt8IcAwK2VLXoGMI543e_3WS3ISM", "foi au destin", "الإيمان بالقدر"},
			{"w28", "1_c7xBlLg-NzLU0yuqMWjMZhykYqU96GU", "mohamed que la paix et la bénédiction d'allah soient sur lui", "محمد صلى الله عليه وسلم"},
			{"w29", "1_rFQK6sAOr0wWLKy8f6AzdCtYsfGxTNx", "croire aux anges1", "الإيمان بالملائكة1"},
			{"w30", "1_yFA2rhJUULy_6fkfJuAW296FmNYA0Uc", "safaa wa maroua", "صفا ومروة"},
			{"w31", "1a4Y57Su6Z7IOhL1ihrBIurVgVlqN2Igu", "diable", "شيطان"},
			{"w32", "1aJUgIZ5Q_Fiuo-EtJhO_iBuXaT3pDxGK", "profession de la foi musulmane", "الشهادتان"},
			{"w33", "1aSIq4IChAxzFJIYVR7-akfuK9D7_9-Kq", "jeûne", "صوم"},
			{"w34", "1aSJQjlb70z5KE1t9GmHzwkDD2IROXcSt", "prière", "صلاة"},
			{"w35", "1aSaIr7ebuZLW8700H6ENbEoTNwPfbsWM", "safaa", "صفا"},
			{"w36", "1a_WdvFgqd4g3aLk-cYprlrv2XIFzMzF8", "tombe", "قبر"},
			{"w37", "1ac8QpzZgOE9V8ZPimfCLOiWZATwMgM-d", "punition divin", "العقاب الإلهي"},
			{"w38", "1amlfb-sRgnjDVMsAeRfMvA3LFPnXuBos", "tawaf (autour de la ka'ba)", "طواف"},
			{"w39", "1arbocTfVzgPrcbGkPMA-PfmCBGHPA7Dy", "kaâba", "الكعبة"},
			{"w40", "1aaAcpwW4Lrte8pMdJyOP6rU1UP9kq4ub", "livres monothéistes", "كتب سماوية"},
			{"w41", "1asIqGGLgLsUe4AJYmZ7siLm5uPWmnxsQ", "coran", "قرآن"},
			{"w42", "1asPDkhYPxOVCrgqMH-6MWTqlgMMz8cbE", "christianisme", "مسيحية"},
			{"w43", "1ax2dtfhC2JQN-Th8cEwMBGC-GAdoTuUF", "maroua", "مروة"},
			{"w44", "1b-QKWrPY1a0hJ2o5nEIVDGH3YNvoAocN", "al madina al munawara", "المدينة المنورة"},
			{"w45", "1b1M9FafWh7wz_Z2J5_8Ek-MnsX7wevtT", "mort", "موت، وفاة"},
			{"w46", "1b86o1Dhdbr3aDpTfmuQzJM644Gkxta7E", "ange", "ملاك، ملائكة"},
			{"w47", "1bDqCfYyIF7d2MGkiJdYfTHy8zKy7j7Eu", "répréhensible", "مكروه"},
			{"w48", "1bFM4r3b2c3NU0cj3AUqdtJhaD9txP5q7", "hypocrisie", "نفاق"},
			{"w49", "1bKC7gKKgzKpvE11Gbb2Jv-B3s43TmLdo", "prophète", "نبي"},
			{"w50", "1bMBM7t3rZw8t402nMn6q4aT7esPQqCjI", "enfer, jahannam", "جهنم"},
			{"w51", "1bX1oYERsI4MOARtFgC22R7g_j8yhaLfl", "judaïsme", "يهودية"},
			{"w52", "1bYLjrdxgVPZIxLYNsfsbn0nUrcMQ4Gp-", "ablution", "وضوء"},
			{"w53", "1bg5mnXZsKWqxw-KgbtaTnuFhPjDP8Vh1", "devoir", "الفرض (واجب ديني)"},
			{"w54", "1bk0LaKQ4ZdMJXBCJU8SlmL36BdgjoRqD", "prière de dohr", "صلاة الظهر"},
			{"w55", "1bkLNgZk5Bvuuh8uGW1w5iR146UprpYnH", "prière de sobh", "صلاة الصبح"},
			{"w56", "1bmIcn-QEudCHXQz_zzJwBLktD1EVJ2Qu", "lapidation des stèles", "رمي الجمرات"},
			{"w57", "1bw3O3yZxx9R39pcXpOypaqdHoP3kk53V", "prière de l'ichâ", "صلاة العشاء"},
			{"w58", "1c0okFKlihRHtQUAbed6wVFYn78rbbTF_", "prière de maghreb", "صلاة المغرب"},
			{"w59", "1c2oSZrW69Ia8TVqmLNM09rMDpTBFd3RZ", "prière de l'asr", "صلاة العصر"},
			{"w60", "1c8n10l-RtSDd-8gQ44UqmeaJA9YzuwJN", "pilliers de la foi2", "أركان الإيمان2"},
			{"w61", "1cFISBp-dDulV4nzdLBfBgtJqDM2pP1uz", "croire aux prophètes2", "الإيمان بالرسل2"},
			{"w62", "1cHWEoJ4QXyuev0mYMRYNNKKQUm9Y5vj8", "croire aux livres monothéistes2", "الإيمان بالكتب السماوية2"},
			{"w63", "1cHYn1Vq8q0Q4Numu1x_zWiLu79Tl7zJD", "croire aux anges2", "الإيمان بالملائكة2"},
			{"w64", "1cSbKBNn6jW0H2LzB3e-LwCIIm9QNmZ8w", "la foi2", "الإيمان2"},
	};
}
