package com.mohamed.barki.asl.resactivity;

import android.app.Activity;
public class ResActivityU extends Activity
{
	public static String[][] resList = new String[][]{
			//الأفعال
			{"u0", "url", "devoir, il faut", "وجَبَ (فعل)"},
			{"u1", "url", "mais", "لَكِن"},
			{"u2", "url", "dialogue2", "محادثة2"},
			{"u3", "url", "pas encore", "ليس بعد"},
			{"u4", "url", "bonne nuit", "ليلة سعيدة"},
			{"u5", "url", "sauf", "ماعدا"},
			{"u6", "url", "finalement", "أخيرا"},
			{"u7", "url", "bravo", "أحسنت"},
			{"u8", "url", "jamais", "أبدا"},
			{"u9", "url", "signe2", "إشارة2"},
			{"u10", "url", "désolé", "آسف"},
			{"u11", "url", "si", "إذا"},
			{"u12", "url", "tu (toi)", "أنت"},
			{"u13", "url", "trouver1", "وجد (فعل)1"},
			{"u14", "1j-yM96_7yeN2hABjlOy8jmaz0vfFfemf", "voter", "انتخب (فعل)"},
			{"u15", "1dFlKjein0ed5mySa4WuDgASImpDIH-xr", "faire sortir", "أخرج (فعل)"},
			{"u16", "url", "répéter1", "كرَّر (فعل)1"},
			{"u17", "url", "se battre, se chamailler, se bagarrer", "خاصم (فعل)"},
			{"u18", "url", "suggéré, proposer", "إقترح (فعل)"},
			{"u19", "url", "moucharder", "وشى (فعل)"},
			{"u20", "url", "promettre", "وعد (فعل)"},
			{"u21", "url", "questionner", "إستجوب (فعل)"},
			{"u22", "url", "expliquer", "شرح (فعل)"},
			{"u23", "url", "hurler", "صاح (فعل)"},
			{"u24", "url", "insulter", "شتم (فعل)"},
			{"u25", "url", "copier1", "نسخ (فعل)1"},
			{"u26", "1iOFkQO-bhXw31jX4zBvQ1KFgK0rog_x1", "écouter", "أصغى (فعل)"},
			{"u27", "url", "envoyer1", "أرسل (فعل)1"},
			{"u28", "url", "apprendre, mémoriser", "حفظ (فعل)"},
			{"u29", "url", "avouer", "إعترف (فعل)"},
			{"u30", "url", "bavarder", "ثرثر (فعل)"},
			{"u31", "url", "équilibrer", "وازن (فعل)"},
			{"u32", "url", "peser, mesurer", "وزن (فعل)"},
			{"u33", "1u0N6w-s5pQ1Op5UjDJmuC4jPvcX2e7fX", "trouver2", "وجد (فعل)2"},
			{"u34", "url", "fuir", "هرب (فعل)"},
			{"u35", "url", "ils, eux", "هم (ضمير)"},
			{"u36", "url", "il, lui", "هو (ضمير)"},
			{"u37", "url", "nettoyer", "نظف (فعل)"},
			{"u38", "url", "détruire", "هدم (فعل)"},
			{"u39", "url", "celui-là", "هذا"},
			{"u40", "url", "descendre", "نزل (فعل)"},
			{"u41", "url", "oublier", "نسي (فعل)"},
			{"u42", "url", "diffuser", "نشر (فعل)"},
			{"u43", "url", "de (préposition)", "من (حرف جر)"},
			{"u44", "1jdeweKd39kE948MVWZq2CZ0N8KSjlCYu", "dormir1", "نام (فعل)1"},
			{"u45", "url", "nous", "نحن (ضمير)"},
			{"u46", "url", "rigoler, blaguer", "مزح (فعل)"},
			{"u47", "url", "effacer", "مسح (فعل)"},
			{"u48", "1hI-XiwB7C9GRk-h274tYkHcbTVumkHF9", "se gargariser", "تمضمض (فعل)"},
			{"u49", "url", "quoi ?", "ماذا ؟"},
			{"u50", "url", "quand ?", "متى ؟"},
			{"u51", "url", "effacer", "محى (فعل)"},
			{"u52", "url", "pour moi, à moi", "من أجلي، لي"},
			{"u53", "url", "que faire ?", "ما العمل ؟"},
			{"u54", "url", "qu'est-ce qui se passe ?", "ماذا يجري ؟"},
			{"u55", "url", "pourquoi ?", "لماذا ؟"},
			{"u56", "url", "ne pas", "لن (حرف نصب)"},
			{"u57", "url", "ne pas", "لم (حرف جزم)"},
			{"u58", "url", "pourquoi pas ?", "لما لا ؟"},
			{"u59", "url", "quand, aussitôt", "لمَّا (حرف جزم)"},
			{"u60", "url", "pour lui, à lui", "له، من أجله"},
			{"u61", "url", "pour (préposition)", "لـ (حرف جر)"},
			{"u62", "url", "résumer, synthétiser1", "لخَّص (فعل)1"},
			{"u63", "url", "pour toi, à toi1", "من أجلك، لك1"},
			{"u64", "url", "il n'aime pas", "لا يُحِبُّ"},
			{"u65", "url", "non", "لا (أداة نهي)"},
			{"u66", "url", "regarder", "نظر (فعل)"},
			{"u67", "url", "combien", "كم ؟"},
			{"u68", "url", "pour", "كي (حرف نصب)"},
			{"u69", "url", "comment ?", "كيف ؟"},
			{"u70", "url", "mentir1", "كذب (فعل)1"},
			{"u71", "url", "détester", "كره (فعل)"},
			{"u72", "url", "quel âge as-tu ?", "كم عمرك ؟"},
			{"u73", "url", "réduire", "قلص (فعل)"},
			{"u74", "16LOGb_utNegs0YteW1wb30eU8mJovQLs", "appeler", "نادى (فعل)"},
			{"u75", "1W-KXVefjTHoT0tdd8Jt-uE-giQfQZANT", "écrire", "كتب (فعل)"},
			{"u76", "url", "tuer", "قتل (فعل)"},
			{"u77", "url", "annuler", "ألغى (فعل)"},
			{"u78", "url", "sauter", "قفز (فعل)"},
			{"u79", "url", "réfléchir", "فكر (فعل)"},
			{"u80", "url", "comprendre", "فهم (فعل)"},
			{"u81", "url", "dans (préposition)", "في (حرف جر)"},
			{"u82", "url", "jeûner", "صام (فعل)"},
			{"u83", "url", "monter", "صعد (فعل)"},
			{"u84", "url", "photographier", "صوَّر (فعل)"},
			{"u85", "url", "tricher", "غشَّ (فعل)"},
			{"u86", "url", "annoncer", "أعلن (فعل)"},
			{"u87", "1hJ4omBWdTAvseXxpXUw1tdCj1K0r3qwM", "verbe à l'impératif présent", "فعل أمر"},
			{"u88", "1hKQsvDjBzcvawa2cTxSEgbbgcx05UHoj", "verbe1", "فعل1"},
			{"u89", "1hLlqmYVw-c0Mt7P1oGPVgrguuvrKVuIg", "verbe2", "فعل2"},
			{"u90", "url", "laver", "غسل (فعل)"},
			{"u91", "url", "frapper", "ضرب (فعل)"},
			{"u92", "url", "divorcer", "طلَّق (فعل)"},
			{"u93", "url", "fréquenter1", "عاشَرَ (فعل)1"},
			{"u94", "url", "tomber", "سقط (فعل)"},
			{"u95", "url", "boire", "شرب (فعل)"},
			{"u96", "url", "douter, soupçonner", "شكَّ (فعل)"},
			{"u97", "1ILE0Z28B0_3DMlQMI-F5TkOuGBuaQRka", "aider", "ساعد (فعل)"},
			{"u98", "url", "voyager", "سافر (فعل)"},
			{"u99", "url", "nager", "سبح (فعل)"},
			{"u100", "url", "dessiner", "رسم (فعل)"},
			{"u101", "url", "falsifier", "زوَّر (فعل)"},
			{"u102", "url", "embelir, décorer", "زيَّن (فعل)"},
			{"u103", "1cUBt5NCXi2OkcyMGEOqBGqiNRdDHc-mi", "sortir", "خرج (فعل)"},
			{"u104", "1cYt4xS7YxlQKjHs9va4E04ZtNK9gEYIx", "caresser", "داعب (فعل)"},
			{"u105", "1cZ2ZkF9qMr-A-D_oa7eOJLIUrtbgfmgA", "entrer", "دخل (فعل)"},
			{"u106", "url", "utiliser1", "إستعمل (فعل)1"},
			{"u107", "1c_fRWWElKbpimkmd1SDWI32eoSGTosPB", "se cacher", "اختبأ (فعل)"},
			{"u108", "1ca1b5386bc9oZnujsYMfvOmLnENSXYak", "sourire", "ابتسم (فعل)"},
			{"u109", "url", "résumer, synthétiser2", "لخَّص (فعل)2"},
			{"u110", "url", "se plaindre", "إشتكى (فعل)"},
			{"u111", "url", "téléphoner", "هتف (فعل)"},
			{"u112", "url", "passer, traverser", "عبر (فعل)"},
			{"u113", "url", "provoquer", "إستفزَّ (فعل)"},
			{"u114", "url", "recevoir", "إستلم (فعل)"},
			{"u115", "url", "fréquenter2", "عاشَرَ (فعل)2"},
			{"u116", "url", "imprimer", "طبع (فعل)"},
			{"u117", "url", "mentir2", "كذب (فعل)2"},
			{"u118", "url", "crier", "صرخ (فعل)"},
			{"u119", "url", "enregistrer", "سجَّل (فعل)"},
			{"u120", "url", "éveiller, alerter", "نبَّه (فعل)"},
			{"u121", "url", "blâmer", "وبخ (فعل)"},
			{"u122", "url", "conduire", "قاد (فعل)"},
			{"u123", "url", "convaincre", "أقنع (فعل)"},
			{"u124", "1caXF8o5K4f1fzpvZUDMqG3X7fuTqCCME", "apporter1", "جلب1 (فعل)"},
			{"u125", "url", "apprendre", "تعلم (فعل)"},
			{"u126", "url", "avertir", "حذر (فعل)"},
			{"u127", "1cel0XFm1K8XJSf9CKSKdWXZ3CIXLBR_K", "rêver", "حلم (فعل)"},
			{"u128", "url", "afficher1", "عرَضَ (فعل)1"},
			{"u129", "url", "afficher2", "عرَضَ (فعل)2"},
			{"u130", "1ciw7tExiOFROpz3D-SQszMiKe6rH4ZFR", "saisir, confisquer", "حجز (فعل)"},
			{"u131", "url", "prépositions", "حرف جر، حروف الجر"},
			{"u132", "url", "adverbes de négation", "حرف جزم، حروف الجزم"},
			{"u133", "1cfrxTILoez7gUwyM-YsErglGPO3FOyiX", "avoir faim1", "جاع (فعل)1"},
			{"u134", "url", "apporter2", "جلب2 (فعل)"},
			{"u135", "url", "jusqu'à", "حتى (حرف نصب)"},
			{"u136", "1cn504_WBfQGL9R35i1Oh3ySo4WvZOH61", "se rebeller, se révolter", "ثار (فعل)"},
			{"u137", "1csqQfTnqdD8A9Z0a9Q5tKqC8oj-DPPYY", "respirer", "تنفس (فعل)"},
			{"u138", "url", "après, ensuite, et puis", "ثُمَّ (حرف عطف)"},
			{"u139", "1csy5UCSY3noI8epxtgPWd9MjHEXfZCdA", "se rappeler, se souvenir", "تذكر (فعل)"},
			{"u140", "1d-6Di5Ek4cHLfKJpl6jGZRVFNFE0uP8R", "supplier", "ترجَّى (فعل)"},
			{"u141", "1d-F6-cDXMWmYAMM5PhUFDh5vwWqk4U5C", "se balader", "تنزَّه (فعل)"},
			{"u142", "1d-eprJzzL1G7-SGcGihTirNqJoHXJ0q-", "souffrir, avoir mal1", "تألم (فعل)1"},
			{"u143", "1d3uzD1ZXDHzOmxRn2FXJUrLDnt1R-Zdb", "suivre", "تبع (فعل)"},
			{"u144", "1d7hGhq89tKDhWFeYC-7Tztx6LD9Y93o2", "imaginer", "تخيل (فعل)"},
			{"u145", "url", "conjonctions de coordination", "حرف عطف، حروف العطف"},
			{"u146", "url", "conjonctions de subordination", "حرف نصب، أداة نصب، حروف النصب، أدواة النصب"},
			{"u147", "1dAov9WRISmwIDbwtbfdlZ84YCq05riBo", "juger", "حكم (فعل)"},
			{"u148", "url", "où ?", "أين ؟"},
			{"u149", "url", "lesquels, lesquelles", "أيُّهما ؟"},
			{"u150", "1dHkTAP58RBBRXoGZlmcrDbjupI3wtApZ", "vendre", "باع (فعل)"},
			{"u151", "1dLMCe-I4X3pH-th6PpvoOSrU45ztujgp", "accomplir", "أنجز (فعل)"},
			{"u152", "1d_ROE_B0NMWwRzCL8is10Y8kwYSQVHK6", "sauver", "أنقذ (فعل)"},
			{"u153", "1dalcmvwYsyQFYG6m44f19zt59QMsZ8lK", "achever", "أنهى (فعل)"},
			{"u154", "1db04rZ1qbvFYufGokiWi2776hSfyN7pG", "se suicider", "إنتحر (فعل)"},
			{"u155", "url", "vous", "أنتم (ضمير)"},
			{"u156", "url", "et (conjonction)", "و، الواو (حرف عطف)"},
			{"u157", "url", "à, jusqu'à (préposition)", "إلى (حرف جر)"},
			{"u158", "url", "que", "أن (حرف نصب)"},
			{"u159", "1dhstZ17WPohcLFIPH5vzKfmNSL783LxO", "mot1", "كلمة1"},
			{"u160", "1ditsodQPkL21InfeZwNtVq007WvzHcuh", "sujet", "مبتدأ"},
			{"u161", "1djg29N9rhV7AQU5kNvhbfP5uoNpfpFx3", "complément", "مفعول به"},
			{"u162", "1dojqR5ffbucdxXsyK5-IftNm9dc3pFOK", "exagérer", "بالغ (فعل)"},
			{"u163", "1dvvj0qBD7SEK4CgtHDdY7VPeH3ipwh9W", "chercher", "بحث (فعل)"},
			{"u164", "1u0N6w-s5pQ1Op5UjDJmuC4jPvcX2e7fX", "trouver3", "وجد (فعل)3"},
			{"u165", "1dzaRYr5wkTjCc3V2PQU92V4mhKeLGhUf", "verbe au présent1", "فعل مضارع1"},
			{"u166", "1e2a5RKe9z6lwScQT0v1vHuWmZI2AIQBZ", "grammaire", "قواعد"},
			{"u167", "1e5v6CgYz0YIc7LRJ-8h3JWrmGqeCdFHH", "i (voyelle)", "كسرة"},
			{"u168", "1eEMzz0BJls3v8kZQnUJzYhc3gZiHU0s5", "sujet1", "فاعل1"},
			{"u169", "1eML24t3qJBWn7WCINtiJGIQekq92YFnk", "a (voyelle)", "فتحة"},
			{"u170", "1ePzc7XHzRpE7aLif4burLYpBGfVL-3R3", "verbe au passé1", "فعل ماض1"},
			{"u171", "1A9ykC1UpvPFGXNeOWP3skODGFU9xcZhq", "demander", "طلب (فعل)"},
			{"u172", "1eV9jvJrueDQ9FymC2uK1Qc0PgSdzVmG6", "o (voyelle)", "ضمة"},
			{"u173", "1eVKISIa8q6M0WzOOK1TXC2w94-3sO1_6", "'", "سكون"},
			{"u174", "url", "par, avec", "بِ، الباء (حرف جر)"},
			{"u175", "1ebFc8e3paG9Z33dx1yBujE0uxu8KCTBL", "phrase1", "جملة1"},
			{"u176", "1ef0s7GlKb2nUL18wnFdMQIi99l2sAvc4", "lettre", "حرف"},
			{"u177", "1eg9U88uJO4swDAZqA_SGgUQPWsGHhEAy", "manger", "أكل (فعل)"},
			{"u178", "url", "complément", "متمم"},
			{"u179", "1ehVuwqR8zlMDqpHM0NVlms0w6gitOFdo", "verbes", "أفعال"},
			{"u180", "1ekz666dY98kGwCLkkKvCel85aVZTLOCV", "croire, penser que", "إعتقد (فعل)"},
			{"u181", "1erosUMVFCkIyaShaDKl_vihQvk6fxzwl", "sujet2", "فاعل2"},
			{"u182", "1f0X6Zr7nR9DTb2iDFr04i16mrtwSTUZZ", "économiser", "إقتصد (فعل)"},
			{"u183", "1f1qEeOlz1DDrW7NXDMRfymok1hxpxkaZ", "perdre", "أضاع (فعل)"},
			{"u184", "1f3yjycf9ZyHvKGwb1C6aVd_QcN_Ixq-y", "rajouter", "أضاف (فعل)"},
			{"u185", "1f8voA07kzQmal7JZnQ8hpzBVBIHJQG4J", "agresser", "إعتدى (فعل)"},
			{"u186", "url", "intervenir", "تدخَّل (فعل)"},
			{"u187", "1f9iRWasa659XbnQGbwp9Zra-ZRMMfO-C", "acheter", "إشترى (فعل)"},
			{"u188", "1fAgOVGS6W4WmQChuImSZGRtjmRVfm3NQ", "allumer", "أشعل (فعل)"},
			{"u189", "1fC8YpX2H6F6EFIEd71Ihs40k2h4FSGpV", "nom inainimé", "إسم جماد"},
			{"u190", "1fEyeJVXq4ORzm9EAVUWwW23ygaXGLbHo", "nom d'animal", "إسم حيوان"},
			{"u191", "1fJQdJiH6X34hfeD61XhfW_iWwQwoin5E", "nom propre1", "إسم علم1"},
			{"u192", "1fJmH6CEXxwF9edE-Qvp41ItewjOhz3Fq", "envoyer2", "أرسل (فعل)2"},
			{"u193", "1fLSz9SjH1BVoipp-r2NcaxlTgC5xHAaP", "utiliser2", "إستعمل (فعل)2"},
			{"u194", "1faBt9dK2ZJPhAJu2FvRCggjkM7GuSog4", "respirer, inhaler", "إستنشق (فعل)"},
			{"u195", "1fecG3vl-ZF49giJKlg9duvk5o8KnODNz", "venir", "أتى (فعل)"},
			{"u196", "1fnne7GRXpXcWluuoLzZ2YdY0a5W-v9Qb", "aimer", "أحبَّ (فعل)"},
			{"u197", "1fpITJB5v4Yigc-QXs_EPVhUcu_a0HrYR", "choisir", "إختار (فعل)"},
			{"u198", "url", "sur (préposition)", "على (حرف جر)"},
			{"u199", "1fwYMCk6d31SOxjNe2BjV0XDffG8jux0g", "verbe au présent2", "فعل مضارع2"},
			{"u200", "1g4USVL350bcrBXDj9CDr2JlKHs_Pm8CF", "verbe au passé2", "فعل ماض2"},
			{"u201", "1gB2wZLngx-jH_DfAmTLgJXYgtFaZBWVv", "Prédicat (linguistique)", "الخبر (نحو)"},
			{"u202", "1gFHSuhuhM5IxR0faJAnaAejbeHX6V03p", "ramper", "حبا (فعل)"},
			{"u203", "1gJQMkIWyu9iGQTX_-cU3HE_9yp-WkfMe", "vouloir", "أراد (فعل)"},
			{"u204", "1gK12ysqsl0DpAoF2kZi2NYu0WRSf2x5t", "exploiter", "إستغل (فعل)"},
			{"u205", "1gLMTkeIrvCGSJvTnmRrOhenlQfx6Sdgl", "arrêter", "إعتقل (فعل)"},
			{"u206", "1gNSWoqyrxo2CcK7LulzHQy43-OzhJWGz", "éteindre", "أطفأ (فعل)"},
			{"u207", "1gOn7d1vBIAzOk0GPPTJeZMyCxNskchp3", "adapter", "تأقلم (فعل)"},
			{"u208", "1gSde54_qHD-Hyj3EqQMNa-O_W2QuWRsR", "marier", "تزوج (فعل)"},
			{"u209", "1gVHF1_sVECoHLEhSB-BGWFOGxRiI64E_", "fumer", "دخن (فعل)"},
			{"u210", "1gY6y0SPFIDjGcC-9W2w-de84R_aKVsfm", "élonger", "تمدد (فعل)"},
			{"u211", "1ggBSBfjklgsZDQnR8mSwMlrew6AK5kLF", "étudier", "درس (فعل)"},
			{"u212", "1gl6wKiOCarpo2VKJy-bnlxALz9DMMnm7", "pousser", "دفع (فعل)"},
			{"u213", "1glR1WPMM2DGDobhC8TCGwcpsmqYEdcP7", "aller", "ذهب (فعل)"},
			{"u214", "1gz3oFK_45t088Ej05fJaAAB2C0O-phjT", "accompagner", "رافق (فعل)"},
			{"u215", "1h21cHu8r2s7VekobrYkNseJF19d5Upy3", "indiquer", "أشار (فعل)"},
			{"u216", "1hCZuuwrXBtcbp7jRwIGb7IeimFamWZnW", "grimper", "تسلق (فعل)"},
			{"u217", "url", "dormir2", "نام (فعل)2"},
			{"u218", "url", "encore", "مرة أخرى"},
			{"u219", "url", "souffrir, avoir mal2", "تألم (فعل)2"},
			{"u220", "url", "assis, s'asseoir", "جلس (فعل)"},
			{"u221", "url", "ranger", "رتب (فعل)"},
			{"u222", "url", "nom propre2", "إسم علم2"},
			{"u223", "url", "nom commun1", "إسم مشترك1"},
			{"u224", "url", "nom commun2", "إسم مشترك2"},
			{"u225", "url", "adjectif1", "صفة1"},
			{"u226", "url", "adjectif2", "صفة2"},
			{"u227", "url", "sujet3", "فاعل3"},
			{"u228", "url", "pour toi, à toi2", "من أجلك، لك2"},
			{"u229", "url", "pour (préposition)", "لِ، اللام (حرف جر)"},
			{"u230", "url", "qui", "من الذي"},
			{"u231", "url", "faire pipi", "تبول (فعل)"},
			{"u232", "url", "faire caca", "تبرز (فعل)"},
			{"u233", "1vV7hrd5JDeKyVeK5cc2i0-Gxj-jgwUxx", "arriver", "وصل (فعل)"},
			{"u234", "13__TvyLASfXm_9nA33DMiyrsyJkEx5PV", "dire", "قال (فعل)"},
			{"u235", "1DlxalmHBCLawD4Yoj75l0fG3jijrfmek", "donner", "منح، أعطى (فعل)"},
			{"u236", "1vxlZMjFH_HycHt0eg73J9lleoMlTMlQb", "faire", "صنع، عمل (فعل)"},
			{"u237", "1mq6Wbubjkw_AcxCE-BNWbU19DRmLJd9d", "habiter", "عاش، سكن (فعل)"},
			{"u238", "1zrh3MZzgNvuft6MoLMam6WXnPLnZ8f7x", "payer", "دفع (فعل)"},
			{"u239", "15AxGXAZUSrAACDPoLxiHETRO_it5cM5i", "rencontrer, rencontre", "إلتقى، واجه (فعل)"},
			{"u240", "1BicYA0GE4OzRgoExIUoJUxRA5lImbZ17", "rester", "بقى (فعل)"},
			{"u241", "1JbkR-6Ms_Qq3-sg2JEK80goFNqlH71UV", "travailler", "اشتغل، عمل (فعل)"},
			{"u242", "1ivwV18zg7W1O10y8itEJ7Lvy7FS8OJhz", "voir", "رأى (فعل)"},
			{"u243", "url", "avoir faim2", "جاع (فعل)2"},
			{"u244", "url", "réserver", "حجز (فعل)"},
			{"u245", "url", "commander", "طلب (فعل)"},
			{"u246", "url", "coller", "لصق (فعل)"},
			{"u247", "url", "copier2", "نسخ (فعل)2"},
			{"u248", "url", "écouter", "استمع (فعل)"},
			{"u249", "url", "essayer", "حاول (فعل)"},
			{"u250", "url", "lire", "قرأ (فعل)"},
			{"u251", "url", "répéter2", "كرَّر (فعل)2"},
			{"u252", "url", "se concentrer", "ركَّز (فعل)"},
			{"u253", "url", "vérifier", "فحص، تحقق (فعل)"},
	};
}
