package com.mohamed.barki.asl.lite.resactivity;

import android.app.Activity;
public class ResActivityV extends Activity
{
	public static String[][] resList = new String[][]{
			//المدرسة
			{"v0", "1RT3jw1Zaq3CrhiL7xtW976wjxati5W-I", "devoir1", "فرضٌ1"},
			{"v1", "1RdTsvVEFpeI523y0CpX_stl1f8hAORHV", "addition", "جمع (عملية حسابية)"},
			{"v2", "1RgFPgmeOh6DEYBWvHnvZ5txmExvhKjVk", "racine carrée", "جذر تربيعي"},
			{"v3", "1Riz3pK0zg00TdsuD5nv6_olYF-CN0DIs", "sciences naturelles", "علوم طبيعية"},
			{"v4", "1RpBvUzTZ7tB9orwTT98CeNY8KdlxddYK", "matières scolaires1", "مادة، مواد دراسية1"},
			{"v5", "1Rs9tDlEhR3bf_oSOHI6z-yQxZm3fNkzY", "sujet", "موضوع"},
			{"v6", "1RvlG44EP3RABkBY8K490lJQECgdu58rY", "soustraction", "طرح (عملية حسابية)"},
			{"v7", "1S7y7EYAx4swyiRFFZ-ogzrHWqn9vhYeC", "comptage", "عدٌّ، حساب"},
			{"v8", "1S95LO9oPto_0J9YnvMjytmX4bVnvWivs", "note", "علامة"},
			{"v9", "1SEjkUG-7dlrdsrFO1YZkChNPC2B5eFTy", "multiplication", "ضرب، جداء (عملية حسابية)"},
			{"v10", "1SRHLWCgGItRk5-maz1zox0DnLYecqmCZ", "double3", "ضِعْف3"},
			{"v11", "1SRnspimooUicrxw8riq9i5PPFiJr4GGU", "table", "طاولة"},
			{"v12", "1SS95saoxdZWDkXE0QPcVL_He2hDOSYTu", "crèche", "روضة الأطفال"},
			{"v13", "1ST37nbHjGFdHAz-BnjZVn2WScbJXy8mh", "cour d'école", "ساحة المدرسة"},
			{"v14", "1SUspyCrtRnW7Z4voBnoTwIes9pMOomA2", "question2", "سؤال2"},
			{"v15", "1SaI00L3jrkxdXnNKc-VUpPI1jJ2RyOpI", "calcul1", "حساب (العدُّ)1"},
			{"v16", "1SgvpR9Ik8crTBWj4Lxg7mR2h0dj9sj9_", "texte", "نص"},
			{"v17", "1SkHecVZeFLbwZRx0X5Kf8oKLOJWsYelp", "armoire1", "خزانة1"},
			{"v18", "1SsNKivOzWZC9vwfcGIO8BPNqlrSFtil0", "géographie1", "جغرافيا1"},
			{"v19", "1SvjG4RwoMBMRqSRacdDee8I_jlcSF5I0", "exercice", "تمرين"},
			{"v20", "1SuN-vj4xtSTGTFAgdXottcIkm6NoVC_0", "université", "جامعة"},
			{"v21", "1T0Xr2-VCowxJWG9Cj7hOtVStzjUL3WS5", "expression écrite", "تعبير كتابي"},
			{"v22", "1T2CUN8p7jscDz-iW5GuaMIHIycElm8c-", "expression", "تعبير"},
			{"v23", "1T5sMvZ3MthXpsxqxdB2NoJ33b1Efipni", "formation professionnelle", "تكوين مهني"},
			{"v24", "1TE3xo_RLeHTOGZaRIeKl0SzeGwTYzDzb", "concentration", "تركيز"},
			{"v25", "1TEohSbsdniFOWKAJ7Am8vCBhCa7Xqfz8", "feuille d'examen", "ورقة الإمتحان"},
			{"v26", "1TQGybYIOOklN2ZzOF1WzVi8dZxY6iwWi", "expression orale", "تعبير شفوي"},
			{"v27", "1TRHyVxyB0yaFNiRutb5y0hE4VBElSP9u", "traduction", "ترجمة"},
			{"v28", "1TWgWQNAPa5a0GzQjE4GSRp0DLdfkypaM", "stylo1", "سيالة1"},
			{"v29", "1TZx53I7My655JVdbNBkQEMdTFgzl3dth", "correction", "تصحيح"},
			{"v30", "1TcP9LSosYQWEd4tcox93M85dYGi0i6Tu", "feuille de dessin", "أوراق الرسم"},
			{"v31", "1Th-lO3TPPfXjc8eg2vjhz9_1tHWaMlGX", "histoire1", "تاريخ1"},
			{"v32", "1Tm0jQhiyDPuVutrkcBZSuo9TJ6xboRkm", "atelier", "ورشة"},
			{"v33", "1iO7vze0zW9QaiOtt7yFbHAhEYhzx5JUR", "nom", "إسم"},
			{"v34", "1TqrToMO613EXHaFeFkOeNSresVYjBtBg", "examen, épreuve1", "إمتحان، اختبار1"},
			{"v35", "1TsiAYmcOah6N9gcpH4JCnZHlZ8UmIiut", "dictée", "املاء"},
			{"v36", "1U0KhxoDeaJ_dpjkY4gFPXjtXz5MGIcoS", "éducation islamique", "تربية إسلامية"},
			{"v37", "1U7v5lU5btLBnG6Ca5CF3mOX87hXa1GMB", "éducation civique", "تربية مدنية"},
			{"v38", "1U9coxekD-BAUHYRpCVcnMCX4FrCoDrEC", "éducation physique", "تربية بدنية"},
			{"v39", "1UDIA_kauhfcFpmwzRv3ZlZPxS7VFgztX", "primaire", "مدرسة إبتدائية"},
			{"v40", "1UEJDjG5BWS-piECeMeyVFzvUFCEs4Hyu", "fournitures scolaires", "أدوات مدرسية"},
			{"v41", "1UFMjUGLi5MqNR9PvUbSkRVQIB6TANdqa", "crayons de couleurs", "أقلام ملونة"},
			{"v42", "1UFp8EvPOat87GHd1KMfahjdfZyiXqMs4", "physique1", "فيزياء1"},
			{"v43", "1UKkpFHetETiSdKu33v_fNcAZr-UX9cVr", "philosophie", "فلسفة"},
			{"v44", "1ULD3tAtsOsXz_xP288GJKyVuslXUrRr6", "passage", "إنتقال"},
			{"v45", "1UZYPX6qlMPlRRzGQJN-Yt1RTHUXRPJrm", "stylo à plume", "قلم الحبر"},
			{"v46", "1UaVs7y6XgQJdIuO6mkJ5cA5HPBm9Hqn4", "division1", "قسمة (عملية حسابية)1"},
			{"v47", "1UX1ir1uZwOXvRgkIl2Do-tFnkK4eNzmh", "classe", "قِسم"},
			{"v48", "1UeU2MXKBI__dcD3AErsIOQAFDiqv8raY", "fraction", "كسْرٌ"},
			{"v49", "1Uf-XSWij7q6Wi-i_ElLRFgiNMHX10zK2", "livre", "كتاب"},
			{"v50", "1UlLbR0Vp_GU7MHK5gigzvcYNPNZOIoQt", "crayon", "قلم رصاص"},
			{"v51", "1Umlf7BoBHoHMDChbBLGPEOwGE_vYv76D", "langue espagnole", "لغة إسبانية"},
			{"v52", "1UoujYAEhqeC2OscgFnEZu7GwjVvqNy43", "équerre", "كوس"},
			{"v53", "1UshlpMCK9FOIC5cqAmsAxfWyoJjDjLKX", "mot2", "كلمة2"},
			{"v54", "1UwHOu2u6XYR2X5u_FKjXzCyQencJT1dU", "langue anglaise", "لغة إنجليزية"},
			{"v55", "1UzCHAFvLrttSGVfqw82c7ZY-rMsn3uj2", "langue amazighe", "لغة أمازيغية"},
			{"v56", "1V0STQpu3OuEC17zkemV0vBiTUewQPRI7", "langue allemande", "لغة ألمانية"},
			{"v57", "1VBiaxz9vuvHwmfIj2L0zYzL4atDTv3K6", "langue", "لغة"},
			{"v58", "1VEgOvpnmif-7sLvDtp5-e1t5y4LBFis1", "langue française", "لغة فرنسية"},
			{"v59", "1VLIUcnzH6u8RVOGNyoeR9qw9DGxpB0NF", "langue arabe", "لغة عربية"},
			{"v60", "1VLXguM6P_qwGKjzRRGdNLjujIbyU6Oyh", "taille-crayon", "مبراة"},
			{"v61", "1VN2tqICELV2dNw5w0kw0ASfu3KJV5PEV", "matière", "مادة دراسية"},
			{"v62", "1VOMS4WV4HEVIz1l-_XKJqcQleP-YYJ4M", "ardoise1", "لوحةٌ1"},
			{"v63", "1VP5XyBQqec0sREOJGGrcSOA5Cp5i8oZ6", "globe terrestre", "مجسم الكرة الأرضية"},
			{"v64", "1VPwopWyb1EB2bdwzwzujct1W0k3oirqu", "collège", "متوسطة"},
			{"v65", "1VRQt8HtphqV7QwASVHDCHS7k-a1HmOHU", "suivi, continuation", "متابعة"},
			{"v66", "1VStQxfbn_kszH-N82omjm4ZZfMltg4Ex", "école", "مدرسة"},
			{"v67", "1VWZ_0QqaQzqvb1kYIQGwbwc9hPS5WsWL", "laboratoire", "مخبر"},
			{"v68", "1VWiuTr3vAIZFEqtjgUE3GNmruXNs21Lo", "cartable1", "محفظة1"},
			{"v69", "1V_mXMjW-8KwI5KCx7gnkyfZ2niAfslL0", "concours", "مسابقة"},
			{"v70", "1VhHgUOlVolhzePmS7DRQQc6VgD20NK4U", "révision", "مراجعة"},
			{"v71", "1XL664FuICMHhTrwtR5SCd3Wfb5DDRi7V", "compas", "مدور"},
			{"v72", "1XGIGD-LKg103wofUfCUpe-9IHQ4W5F2C", "trousse", "مقلمة"},
			{"v73", "1XLeBriHO410NBHKaSmPIO00Wjgp_5mJu", "vocabulaire", "مفردات"},
			{"v74", "1XS2MYeyTxJJ1HBV5i3cvcLIcNFpNPOST", "connaissance", "معرفة"},
			{"v75", "1XT1JfkjHBpNs-sWOZgaivTKLnUAGdAxg", "compétition", "منافسة"},
			{"v76", "1XU_1ivvzauKPGWOLvo2gNRc2SVFzYn8G", "gomme", "ممحاة"},
			{"v77", "1XVqlBpw8YVON_TZs-FFyN8h_V4Jxrsrl", "bureau1", "مكتب1"},
			{"v78", "1XXpz-RScySg3WH1mn8_jzZgHQkMorJmY", "refaire l'année", "أعاد السنة"},
			{"v79", "1Xe37ye5TrRGlz572clN1D83ro_jhx9mz", "punition", "عقاب"},
			{"v80", "1XetgwAdLKPvVFriKKhIysdEi0EAKyUq4", "échec", "رسوب"},
			{"v81", "1Xk9GEnn_Y1HvANosnJB4kfWWVod12HNl", "devoir2", "فرضٌ2"},
			{"v82", "1XnuOAhg3IlQksxeNAxFhNufqfOzKbvMs", "rapporteur", "منقلة"},
			{"v83", "1XuFwWgfNXii4zSbq8r6GHvkzopfj-_Mk", "compréhension", "فهْمٌ"},
			{"v84", "1Y0xb9UIoZnS2UTmaxzolYUB6WbWRvN1N", "ardoise2", "لوحةٌ2"},
			{"v85", "1Y9FpGM8X1QhORkVZ5HNXN-FYWfDiOv0l", "lycée", "ثانوية"},
			{"v86", "1XzblQ-DDhBJQmLxSmQ0bm9QayBDcFtjY", "mathématiques", "رياضيات"},
			{"v87", "1YMbTEFnLvSJVOsCakDo76KJKa-lXaILH", "reliure", "غلاف"},
			{"v88", "1YUjVDxEY9dPUiJfAimqIhiLhyNgbMuIV", "carnet", "دفتر"},
			{"v89", "1YbuoeUT7oLoCJCaF3uwY29FzFZaFPpTs", "réponse", "جواب"},
			{"v90", "1Yc0n9cW4dVvM1B3vjUXlIiH7J3-WOVMH", "corriger", "صحح"},
			{"v91", "1Yg3X4JTeQETT7O5CO6Dr2UhuTpD1Ax07", "gravité", "الجدية"},
			{"v92", "1Yi23fU4SPibKbA0hrynyxeWhP5FjuDa-", "préservation", "الحفظ"},
			{"v93", "1Yo3lu2SVtRDzqpaoUGxqz7MSoDk9GiS-", "lettres", "حروف"},
			{"v94", "1YznjX_eNx1BMidZnveePZnlVPq2qlJfd", "phrase2", "جملة2"},
			{"v95", "1Z-YtIiVEiyZLSWcJXcytGZYtoRPTuw1H", "réussi", "نجح"},
			{"v96", "1Z29ukkDn-PuV_nDKg0uGWUsXSGt27ERf", "tiroir", "دُرج"},
			{"v97", "url", "histoire", "قصة"},
			{"v98", "url", "art", "فن"},
			{"v99", "url", "orthographe", "هجاء"},
			{"v100", "url", "histoire2", "تاريخ2"},
			{"v101", "url", "géographie2", "جغرافيا2"},
			{"v102", "url", "musique", "موسيقى"},
			{"v103", "url", "poésie", "الشِّعر"},
			{"v104", "url", "récréation", "فترة الراحة"},
			{"v105", "url", "cartable2", "محفظة2"},
			{"v106", "url", "cahier", "كراس"},
			{"v107", "url", "géometrie", "هندسة"},
			{"v108", "url", "littérature", "مؤلفات"},
			{"v109", "url", "lecture", "قراءة"},
			{"v110", "url", "langue des signes", "لغة الإشارة"},
			{"v111", "url", "repas", "وجبة"},
			{"v112", "url", "technologie", "التكنلوجيا، علوم التقنية"},
			{"v113", "url", "physique2", "فيزياء2"},
			{"v114", "url", "chimie", "كيمياء"},
			{"v115", "url", "stylo2", "سيالة2"},
			{"v116", "url", "recherche scientifique", "بحث علمي"},
			{"v117", "url", "leçon", "درس"},
			{"v118", "url", "examen, épreuve2", "إمتحان، اختبار2"},
			{"v119", "url", "matières scolaires2", "مادة، مواد دراسية2"},
			{"v120", "url", "récréation", "إيقاع"},
			{"v121", "url", "division2", "قسمة (عملية حسابية)2"},
			{"v122", "url", "somme", "مجموع"},
			{"v123", "url", "différence", "فرق"},
			{"v124", "url", "opération", "عملية حسابية"},
			{"v125", "url", "addition par rétention", "الجمع بالإحتفاظ"},
			{"v126", "url", "soustraction par rétention", "الطرح بالإحتفاظ"},
			{"v127", "url", "calcul2", "حساب (العدُّ)2"},
	};
}
