package com.mohamed.barki.asl.lite.resactivity;


import android.app.Activity;

@SuppressWarnings("SpellCheckingInspection")
public class ResActivityB extends Activity
{
	public static String[][] resList = new String[][]{
			//الصفات الحالات والأضداد
			{"b0", "1OLoLNDqGErFlCY1v06vV9WXV1MtHlMwg", "tumultueux", "مشاغب"},
			{"b1", "url", "bavard", "ثرثار"},
			{"b2", "1btbWkePXFXlQJMsV-XabuoBV-ip2KQG7", "sale1", "متسخ1"},
			{"b3", "url", "utile", "مفيد"},
			{"b4", "url", "valeur", "قيمة"},
			{"b5", "url", "difficulté", "عائق"},
			{"b6", "url", "important", "مهم"},
			{"b7", "1iArZdN5qjZho4A8ylvr-33q58aBdr1R2", "riche1", "غني، ثري1"},
			{"b8", "url", "assoiffé", "عطش"},
			{"b9", "url", "désobéissant", "عاصي"},
			{"b10", "url", "fatigué", "تعب"},
			{"b11", "url", "rapide", "سرعة، سريع"},
			{"b12", "1pGQK6urd5pmHn9dEtQk4ERRgcC0da5uV", "comportement", "سلوك"},
			{"b13", "url", "abstention", "إمتناع"},
			{"b14", "1aq-nvG4rSCGX-6cUdcDOXEHpI9k1-l2T", "traître", "خائن"},
			{"b15", "1bWzbBDncE_5DR3-w-VEnW-LbVd7DPIh2", "fâché", "غضبان"},
			{"b16", "1tX1eAYjvqZm8X6jsQ9YAgFyN7DH9t8Yd", "heureux", "سعيد"},
			{"b17", "1H4Abd8_6KOXzek8_vs9hCzpVHnGIQRT4", "triste", "حزين"},
			{"b18", "14JNFlE-hS_H4cfdQgYIztsfPTa3e5PnM", "lent", "بطيء"},
			{"b19", "url", "idiot", "أحمق"},
			{"b20", "1efaWwHf0--9dGpYFo5nJo9i9jANeuWCV", "calme1", "هادئ1"},
			{"b21", "1hy3uInK0WTV-1m15Hw4qQ79RioN-7NLp", "simple", "بسيط"},
			{"b22", "1U7kI_QCYuM-eO31FHvyCCVXx9p_7Hwyv", "avare1", "بخيل1"},
			{"b23", "1KdasGhmZ8AwtPixzJCq3c9AXQflWto46", "avare2", "بخيل2"},
			{"b24", "url", "meilleur", "أحسن"},
			{"b25", "url", "bruit", "ضجيج"},
			{"b26", "14A6y7boQ8M1EogDAeuYzft0ziC2EyD4d", "propre", "نظيف"},
			{"b27", "1VwmIj7wJVLTNUXvPY5-ccMqH0rrbELGc", "réveillé", "مستيقظ"},
			{"b28", "url", "suspendu", "عالق"},
			{"b29", "1Hpf5TWvD6JAOAqylx8LnN2vmWuA0yjir", "sérieux", "جِدي"},
			{"b30", "url", "injuste", "غير عادل"},
			{"b31", "1hB7aLAdm-RhvmHP3w7LC9-kv0gCfJfGl", "long", "طويل"},
			{"b32", "url", "non bénéfique", "غير مفيد"},
			{"b33", "1uXYNh54Zg65dKNe8In2Yf1khwsWxCsp_", "bête", "غبي"},
			{"b34", "url", "étrange", "غريب"},
			{"b35", "url", "bizarre", "عجيب"},
			{"b36", "1E7aJKGib1_Tj_yJw_s6-TubQrkMgqcBD", "hypocrite", "منافق"},
			{"b37", "url", "meilleur", "أفضل"},
			{"b38", "url", "adaptation", "تأقلم"},
			{"b39", "1dDKtAJNx1on81a_WYcyMTcP4_h6ODUzC", "fainéant", "كسول"},
			{"b40", "1FnZAhmfM2mCfLmN-rn1ngRYa-kjABYV6", "gentil", "لطيف"},
			{"b41", "17bf2j0lDxInim948cLo5e_aK-9XIUP6W", "rusé", "ماكر"},
			{"b42", "url", "occupé", "مشغول"},
			{"b43", "1g4RzlL8cc7qSM1q9Pe6xsiceIAxtIKU5", "jaloux", "غيور"},
			{"b44", "1fyoDWWkJl1aUmvUta1w4ckSRcKGjHuye", "pauvre1", "فقر، فقير1"},
			{"b45", "1t1DOkcUyGEIdvDm5MBWqFplNmI-JC05S", "méchant", "قبيح"},
			{"b46", "1Jd_hB13ytBhYzeSNsnxr6iq3rwbNzGJh", "atroce", "شنيع"},
			{"b47", "1dbD1MJcHw5IMD7LBdlrMe3q24itUSYDi", "courageux", "شجاع"},
			{"b48", "1lkI9--oUm-DK8zqCU4EOrAzzutxDcy5Q", "stress", "قلق"},
			{"b49", "url", "surpris", "مندهش، متعجب، دهشة"},
			{"b50", "1jf1CV5uRgH0A8TwDB9P8aTB72oUfYNIx", "peur", "خائف"},
			{"b51", "1jfUFgWSsWa8OvBjTw4SPnB4g1yISqzWx", "glouton", "طماع"},
			{"b52", "1jg57FuUWYd4hSAPOw9rqHnka7fYPreqJ", "bienfaisant", "كريم"},
			{"b53", "1ji2w1QdLnzADHKB1dKCrCtM2LXqyt3Nx", "petit", "صغير"},
			{"b54", "1jwiEJa-p27XJ1iGhJpi1jasYKZ-Dw45M", "grand", "كبير"},
			{"b55", "1jxoZSoZysVuU0wxKvK__JRvfDfVT5_qK", "humide", "مبتل"},
			{"b56", "1jy0XNoU2f2ZSPjmunzKfbqL_vvWU9KEX", "sec", "جاف"},
			{"b57", "1k0AHAzvap14nImuO0HSGD3xRWelSR7G5", "lisse", "أملس"},
			{"b58", "1k2_izSui8sKaDEBJq1HFQPP7SHrqG0XG", "rugueux", "خشن"},
			{"b59", "1k4Bi_OQDlVuX5Yrhl6bsTNGj08uMXxM4", "cruel", "قاسي"},
			{"b60", "1kAxZ34NvKlCCFBQN0yksyfqoBAyR7ANv", "mince", "رفيع"},
			{"b61", "1kDs2mijc0_q9nvDhQnbmxoExxCvfS9j0", "épais", "غليظ"},
			{"b62", "1kExyZ4EyZQ9tYhpUqtoLC2wSz1Btlyag", "froid", "بارد"},
			{"b63", "1kSgk11aGj9vGe0jAaVTUeJKLGptgO-Y5", "chaud", "ساخن"},
			{"b64", "1kbEB57OmJcLzXVYQl-p9rJZsrFcx4Q34", "nouveau", "جديد"},
			{"b65", "1kjPPrJdeX1fByo8qSeWGmu2-QmVXVNL_", "ancien", "قديم"},
			{"b66", "1kn4Qm1lf9HhPTykoDy1qJXJQUl2m5TNh", "intelligent", "ذكي"},
			{"b67", "1kvuiQXmD-NMh90cbmvnxViMVzqAaCtDz", "modeste", "متواضع"},
			{"b68", "1l21J2zwZVy4z-8FL90FBFu_AMLjI2zj4", "arrogant", "متكبر"},
			{"b69", "1l2FlDTSM-oWlFvSQI7Q9n6CvgWBSTdIv", "léger", "خفيف"},
			{"b70", "1l7JV0oiUhxnpdjnFati_-aD-TORCsP2b", "lourd", "ثقيل"},
			{"b71", "1lCnJmID0KhCU7mhI8pmHln_uJ2zgdvW6", "mince", "نحيل"},
			{"b72", "1lCp6a3Q3q-xVQXy6WROhywf7Etf4kZjJ", "épais", "ثخين"},
			{"b73", "1lFZ_R0REJz1KYJ_PWKksm438hcr5Jaj4", "court", "قصير"},
			{"b74", "1lHlCpDvnL1ilOMEb0W3PvxxhReVThVTQ", "horrible", "بشع"},
			{"b75", "1lR2kG5seegeNGMZSVGoeSLO7JHYdEMTs", "joli", "جميل"},
			{"b76", "1lRyzNyQhifhH2ruQq-RdujcEGKk33sAI", "timide", "خجول"},
			{"b77", "1lWS47pkxbZf6p_H1vGivsslI1khIRkfA", "vite", "سريع"},
			{"b78", "1lTXrRFJIJdD8bVArnm9BeeH_ScAHu1Sq", "neural", "عصبي"},
			{"b79", "1kHTaOns0qyf7RpEYi7Pb9kUUKsvIO3c1", "haute", "عالي"},
			{"b80", "1hmqbWfr-2e9xIpxtn-LEzhVirlrTWHu-", "bas", "منخفض"},
			{"b81", "1ha-xCnEEVfuW8OKeWfpx-ty08jFWzWJY", "fermé", "مغلق"},
			{"b82", "1hSwqCFN_qbDriTu6r_erN3U3GxHkjfm1", "ouvert1", "مفتوح1"},
			{"b83", "1hj0DE2QhSHASIAu7mLYioW3Q37dr4HVU", "gauche", "يسار"},
			{"b84", "1i457qeKDBho0mlYKASVbDEfl7fN4_hkx", "droite", "يمين"},
			{"b85", "url", "sale2", "متسخ2"},
			{"b86", "url", "doudou", "مُمل"},
			{"b87", "url", "joyeux", "مبتهج، بهجة"},
			{"b88", "url", "calme2", "هادئ2"},
			{"b89", "url", "amoureux", "مغرم، واقع في الحب"},
			{"b90", "url", "dégoûté", "مشمئز"},
			{"b91", "url", "l'ennui", "مَلل"},
			{"b92", "url", "déçu", "خائب الأمل، خيبة أمل"},
			{"b93", "url", "stressé", "مضغوط عصبيا، ضغط عصبي"},
			{"b94", "url", "ouvert2", "مفتوح2"},
			{"b95", "url", "lutin", "قزم"},
			{"b96", "url", "émotions, sentiments", "عواطف، مشاعر"},
			{"b97", "url", "trac", "رهاب المسرح"},
			{"b98", "url", "étonnement", "دهشة"},
			{"b99", "url", "refoulement", "قمع"},
			{"b100", "url", "fierté", "فخر"},
			{"b101", "url", "jaloux", "غيرة"},
			{"b102", "url", "frustation", "إحباط"},
			{"b103", "url", "hésitation", "تردد"},
			{"b104", "url", "regret", "ندم"},
			{"b105", "url", "excitation", "إثارة"},
			{"b106", "url", "colère", "غضب"},
			{"b107", "url", "déception", "خيبة الأمل"},
			{"b108", "url", "peine", "مشقة، شاق"},
			{"b109", "url", "vexation", "إنزعاج"},
			{"b110", "url", "tradition", "تقليدي"},
			{"b111", "url", "bronzage", "تسفع"},
			{"b112", "url", "pauvre2", "فقر، فقير2"},
			{"b113", "url", "riche2", "غني، ثري2"},
			{"b114", "url", "gras", "سمين"},
			{"b115", "url", "confort, confortable", "راحة، مريحة"},
			{"b116", "url", "repos", "استراحة"},
			{"b117", "url", "câlin", "محبوب"},
			{"b118", "url", "doucement", "بلطف"},
	};
}
