package com.mohamed.barki.asl.lite.resactivity;

import android.app.Activity;

@SuppressWarnings("SpellCheckingInspection")
public class ResActivityS extends Activity
{
	public static String[][] resList = new String[][]{
			//التواصل
			{"s0", "url", "image", "صورة"},
			{"s1", "url", "toujours", "يوميا، دائما"},
			{"s2", "url", "nécessaire", "ضروري"},
			{"s3", "url", "proposition", "إقتراح"},
			{"s4", "url", "il n'y a pas", "لا يوجد"},
			{"s5", "url", "non", "لا (حرف جزم)"},
			{"s6", "url", "ce n'est pas moi", "لست أنا"},
			{"s7", "url", "pronom", "لقب"},
			{"s8", "url", "signe1", "إشارة1"},
			{"s9", "url", "information", "خبر"},
			{"s10", "url", "secret", "سر"},
			{"s11", "url", "on verra", "سنرى"},
			{"s12", "url", "verbal", "شفوي"},
			{"s13", "url", "perte", "خسارة"},
			{"s14", "url", "discours", "خطاب"},
			{"s15", "url", "toujours comme ça", "دائما هكذا"},
			{"s16", "url", "il le mérite", "يستحق ذلك"},
			{"s17", "url", "couper la parole", "قاطع الكلام"},
			{"s18", "url", "enveloppe postale", "ظرف بريدي"},
			{"s19", "url", "c'est possible", "هذا ممكن"},
			{"s20", "url", "comme ça", "هكذا"},
			{"s21", "url", "ça c'est dangereux", "هذا خطير"},
			{"s22", "url", "c'est correct", "هذا صحيح"},
			{"s23", "url", "c'est impossible", "هذا غير ممكن"},
			{"s24", "url", "ça suffit", "يكفي"},
			{"s25", "url", "oui", "نعم"},
			{"s26", "url", "ça c'est sûr", "هذا أكيد"},
			{"s27", "url", "s'il tu plaît, stp", "من فضلك"},
			{"s28", "url", "débat", "مناقشة"},
			{"s29", "url", "indication", "معلومة"},
			{"s30", "url", "récentes nouvelles", "مستجدات"},
			{"s31", "url", "impossible", "مستحيل"},
			{"s32", "url", "bonsoir", "مساء الخير"},
			{"s33", "url", "je sais", "أعلم"},
			{"s34", "url", "pardon", "العفو، المعذرة"},
			{"s35", "url", "est-ce que?, question", "هل ؟، سؤال"},
			{"s36", "url", "communication", "تواصل"},
			{"s37", "url", "pour toi", "لك"},
			{"s38", "url", "obligation", "إلتزام"},
			{"s39", "url", "adresse", "عنوان"},
			{"s40", "url", "silence", "صمت"},
			{"s41", "url", "chance", "حظ"},
			{"s42", "url", "ou bien, soit", "أو، إمَّا"},
			{"s43", "url", "au revoir1", "إلى اللقاء1"},
			{"s44", "url", "dialogue1", "محادثة1"},
			{"s45", "url", "correspondance", "تراسل"},
			{"s46", "url", "n'importe quoi", "أيُّما"},
			{"s47", "url", "aussi", "أيضا"},
			{"s48", "url", "certainement", "أكيد"},
			{"s49", "url", "à peu près", "تقريبا"},
			{"s50", "url", "connaissance", "تفاهم"},
			{"s51", "url", "nouvelle", "خبر"},
			{"s52", "url", "bien", "حسن"},
			{"s53", "url", "journal", "جريدة"},
			{"s54", "url", "symbole", "رمز"},
			{"s55", "url", "lettre", "رسالة"},
			{"s56", "url", "peut-être", "ربما"},
			{"s57", "url", "bonjour1", "صباح الخير1"},
			{"s58", "url", "bon appétit1", "شهية طيبة1"},
			{"s59", "url", "merci", "شكرا"},
			{"s60", "url", "ne sait pas", "لا يعرف"},
			{"s61", "url", "ça va", "لا بأس"},
			{"s62", "url", "ne peut pas", "لا يستطيع"},
			{"s63", "url", "à moi", "لي"},
			{"s64", "url", "pour lui", "من أجله"},
			{"s65", "url", "déterminant", "المحدد"},
			{"s66", "url", "adverbe", "ظرف"},
			{"s67", "url", "épiphanie", "إستيعاب"},
			{"s68", "url", "prénom", "إسم أول"},
			{"s69", "url", "interface", "واجهه المستخدم"},
			{"s70", "url", "bonjour2", "صباح الخير2"},
			{"s71", "url", "s'il vous plaît, svp", "من فضلكم"},
			{"s72", "url", "consigne", "تعليمة"},
			{"s73", "url", "respecte", "احترام"},
			{"s74", "url", "application", "تطبيق"},
			{"s75", "url", "facebook", "فيسبوك"},
			{"s76", "url", "youtube", "يوتيوب"},
			{"s77", "url", "twitter", "تويتر"},
			{"s78", "url", "messenger", "تطبيق ماسنجر"},
			{"s79", "url", "tik tok", "تيك توك"},
			{"s80", "url", "instagram1", "انستجرام1"},
			{"s81", "url", "instagram2", "انستجرام2"},
			{"s82", "url", "instagram3", "انستجرام3"},
			{"s83", "url", "grindr", "جريندر"},
			{"s84", "url", "tinder", "تطبيق تيندر"},
			{"s85", "url", "telegram", "تطبيق تيليجرام"},
			{"s86", "url", "snapshot", "تطبيق سنابشوت"},
			{"s87", "url", "twitch", "تطبيق تويتش"},
			{"s88", "url", "google", "جوجل، قوقل"},
			{"s89", "url", "discord", "تطبيق ديسكورد"},
			{"s90", "url", "disney +", "ديزني +"},
			{"s91", "url", "netflix", "نيتفليكس"},
			{"s92", "url", "pinterest", "بينتريست"},
			{"s93", "url", "amazon", "تطبيق أمازون"},
			{"s94", "url", "whatsapp", "واتساب"},
			{"s95", "url", "linkedin", "لينكدإن"},
			{"s96", "url", "google maps", "خرائط جوجل"},
			{"s97", "url", "rendez-vous", "موعد، ميعاد"},
			{"s98", "url", "politesse", "أدب، خُلُق"},
			{"s99", "url", "au revoir2", "إلى اللقاء2"},
			{"s100", "url", "bon appétit2", "شهية طيبة2"},
			{"s101", "url", "rare, rarement", "نادر، نادراً"},
			{"s102", "url", "souvent", "غالباً"},
			{"s103", "url", "pareil, même, aussi", "نفس الشيء، نفسه، أيضاً"},
			{"s104", "url", "avec", "مع (حرف عطف)"},
			{"s105", "url", "ensemble", "معاً"},
	};
}
