package com.mohamed.barki.asl.lite.resactivity;

import android.app.Activity;
public class ResActivityS extends Activity
{
	public static String[][] resList = new String[][]{
			//التواصل
			{"s0", "url", "image", "صورة"},
			{"s1", "url", "toujours", "دائما"},
			{"s2", "url", "nécessaire", "ضروري"},
			{"s3", "url", "proposition", "إقتراح"},
			{"s4", "url", "il n'y a pas", "لا يوجد"},
			{"s5", "url", "non", "لا (حرف جزم)"},
			{"s6", "url", "ce n'est pas moi", "لست أنا"},
			{"s7", "url", "pronom", "لقب"},
			{"s8", "url", "signe1", "إشارة1"},
			{"s9", "url", "information", "خبر"},
			{"s10", "url", "secret", "سر"},
			{"s11", "url", "on verra", "سنرى"},
			{"s12", "url", "verbal", "شفوي"},
			{"s13", "url", "perte", "خسارة"},
			{"s14", "url", "discours", "خطاب"},
			{"s15", "url", "toujours comme ça", "دائما هكذا"},
			{"s16", "url", "il le mérite", "يستحق ذلك"},
			{"s17", "url", "couper la parole", "قاطع الكلام"},
			{"s18", "url", "enveloppe postale", "ظرف بريدي"},
			{"s19", "url", "c'est possible", "هذا ممكن"},
			{"s20", "url", "comme ça", "هكذا"},
			{"s21", "url", "ça c'est dangereux", "هذا خطير"},
			{"s22", "url", "c'est correct", "هذا صحيح"},
			{"s23", "url", "c'est impossible", "هذا غير ممكن"},
			{"s24", "url", "ça suffit", "يكفي"},
			{"s25", "url", "oui", "نعم"},
			{"s26", "url", "ça c'est sûr", "هذا أكيد"},
			{"s27", "url", "s'il tu plaît, stp", "من فضلك"},
			{"s28", "url", "débat", "مناقشة"},
			{"s29", "url", "indication", "معلومة"},
			{"s30", "url", "récentes nouvelles", "مستجدات"},
			{"s31", "url", "impossible", "مستحيل"},
			{"s32", "url", "bonsoir", "مساء الخير"},
			{"s33", "url", "je sais", "أعلم"},
			{"s34", "url", "pardon", "العفو، المعذرة"},
			{"s35", "url", "question1", "سؤال1"},
			{"s36", "url", "communication", "تواصل"},
			{"s37", "url", "pour toi", "لك"},
			{"s38", "url", "obligation", "إلتزام"},
			{"s39", "url", "adresse", "عنوان"},
			{"s40", "url", "silence", "صمت"},
			{"s41", "url", "chance", "حظ"},
			{"s42", "url", "ou bien, soit", "إمَّا"},
			{"s43", "url", "au revoir", "إلى اللقاء"},
			{"s44", "url", "dialogue1", "محادثة1"},
			{"s45", "url", "correspondance", "تراسل"},
			{"s46", "url", "n'importe quoi", "أيُّما"},
			{"s47", "url", "aussi", "أيضا"},
			{"s48", "url", "certainement", "أكيد"},
			{"s49", "url", "à peu près", "تقريبا"},
			{"s50", "url", "connaissance", "تفاهم"},
			{"s51", "url", "nouvelle", "خبر"},
			{"s52", "url", "bien", "حسن"},
			{"s53", "url", "journal", "جريدة"},
			{"s54", "url", "symbole", "رمز"},
			{"s55", "url", "lettre", "رسالة"},
			{"s56", "url", "peut-être", "ربما"},
			{"s57", "url", "bonjour1", "صباح الخير1"},
			{"s58", "url", "bon appétit", "شهية طيبة"},
			{"s59", "url", "merci", "شكرا"},
			{"s60", "url", "ne sait pas", "لا يعرف"},
			{"s61", "url", "ça va", "لا بأس"},
			{"s62", "url", "ne peut pas", "لا يستطيع"},
			{"s63", "url", "à moi", "لي"},
			{"s64", "url", "pour lui", "من أجله"},
			{"s65", "url", "déterminant", "المحدد"},
			{"s66", "url", "adverbe", "ظرف"},
			{"s67", "url", "épiphanie", "إستيعاب"},
			{"s68", "url", "prénom", "إسم أول"},
			{"s69", "url", "interface", "واجهه المستخدم"},
			{"s70", "url", "bonjour2", "صباح الخير2"},
			{"s71", "url", "s'il vous plaît, svp", "من فضلكم"},
			{"s72", "url", "consigne", "تعليمة"},
			{"s73", "url", "respecte", "احترام"},
	};
}
