package com.mohamed.barki.asl.resactivity;

import android.app.Activity;
public class ResActivityP extends Activity
{
	public static String[][] resList = new String[][]{
			//وثائق إدارية
			{"p0", "url", "carte d'abonnement", "بطاقة الإشتراك"},
			{"p1", "url", "bilan financier", "حصيلة مالية"},
			{"p2", "1-71s2zsW7dyjead9XretuCswrgbf8s5N", "récépissé", "وصل"},
			{"p3", "1-nDWh1kYjGwpQCGj5NKROPFPqy7ra4eM", "certificat de non-activité", "شهادة عدم العمل"},
			{"p4", "1-Afb79wGd32yRk17VFTI4hoN4vhPYO0J", "certificat de scolarité", "شهادة مدرسية"},
			{"p5", "1-GSx9f0UQnQrc3nOoMA4d5P_jRfF7I4u", "facture d'électricité", "فاتورة الكهرباء"},
			{"p6", "1-Pu-1CNV_TP1QPe0hL5m43jyyqdIp_M_", "facture de gaz", "فاتورة الغاز"},
			{"p7", "1-Q8Iz6udRrBX2QCDeR0KAEVXndC15O-k", "attestation de succès", "شهادة النجاح"},
			{"p8", "1-R5Ss00-Unx4sidKIGGXNnQEB1LcBRVk", "certificat de décès", "شهادة الوفاة"},
			{"p9", "1-h3pMKIIPtfAwdcWK0f2sGrm6BQw1FiX", "fiche familiale", "شهادة عائلية"},
			{"p10", "1BOGO8wVoe9rjeP2csRiBPwKroExsRI9v", "extrait de casier judiciaire", "شهادة السوابق العدلية"},
			{"p11", "1BOpoZvXL0QjFB-8aEWCU6PfCCWw1BXfE", "attestation de travail", "شهادة العمل"},
			{"p12", "1BRRtVBn7q5KT_hOnYQZYCErFxD0UkbbE", "extrait de naissance", "شهادة الميلاد"},
			{"p13", "11rx9G96wKMSgvlpPDTDdmXwRpcNmqrka", "registre de commerce", "سجل تجاري"},
			{"p14", "1-wv9yBcnW2xw2kE-Y4J9hwr9oCAYYDkt", "certificat de résidence", "شهادة الإقامة"},
			{"p15", "1-xX1GGPEgqIxG574OmKCVvySWjQXyKnh", "certificat de nationalité", "شهادة الجنسية"},
			{"p16", "1052axcu111bAgtq8WcE2FNr9iyDPKrLI", "carnet de chèques", "دفتر الصكوك"},
			{"p17", "105Fa20rsUo6EtWvKlWJXEyi5YaOFLYGE", "livret de famille", "دفتر عائلي"},
			{"p18", "1067QDn64g3J7sXYDrXL722Dm70INnsMO", "permis de conduire", "رخصة السياقة"},
			{"p19", "108AVXwfigpsj5IRsUupyCUAhktybD9p9", "mutation", "تحويل"},
			{"p20", "10Bmj-LEsl-FIDR0En8PCyWSTfR4o5X7r", "autorisation paternelle", "تصريح أبوي"},
			{"p21", "10IEi3q3PeZH2jMZTl93ZVcbxxp2mlvYl", "passeport", "جواز السفر"},
			{"p22", "10JWBcaeHZUn5b6P6aJo04RkzN7q92f7Y", "arrêté", "قرار"},
			{"p23", "10R0xipOHViYusEmp78mn451MuvZzUiHT", "vignette auto", "قسيمة السيارات"},
			{"p24", "10bY-8BDR5k2MC1ngSjNyJAap5bJMQeNF", "fiche de paie", "كشف الراتب"},
			{"p25", "10gtBhw8r-mJ3VNMaENPgGQvFeqVZqPP9", "contrôle technique", "مراقبة تقنية"},
			{"p26", "10h8WGOe00Xky5GR_4kKa_hEMSbpEdnzD", "retraite", "تقاعد"},
			{"p27", "10nGd_FcplIiY7AtOBuxbFg_f-fIYW5G_", "documents administratifs", "وثائق إدارية"},
			{"p28", "10quXDPHqXDIr6qWTyngbUVhTpux6LJqG", "timbre fiscale", "طابع جبائي"},
			{"p29", "10sp6Z6AaHhrXmwULQadwV6pPQdmRTTPa", "timbre", "طابع بريدي"},
			{"p30", "10ybZ3GEyHpBKzOjbvD9NQdbvjOJ91xnT", "chèque", "صك"},
			{"p31", "11AmCJ1CFIlvAoR-d3RpbJY9gWLBoThiE", "facture d'eau", "فاتورة الماء"},
			{"p32", "11HiMUaIHZ6x5aho7X2ozeQ059gdOzzE9", "acte de mariage", "عقد الزواج"},
			{"p33", "11N7rc_TRJYqx80GtR0jgV8JQ2oBtPxl_", "demande manuscrite", "طلب خطي"},
			{"p34", "11QfoR4n-MO_hVvhj45uyusbxUO4YRs8i", "comptabilité", "محاسبة"},
			{"p35", "15EIg_W2kwaC2zUvbkgGGgFopargP5wdU", "journal officiel2", "جريدة رسمية2"},
			{"p36", "11W8TB1w-UDy_I6_guDiiJsesGHz0PE-H", "administration", "إدارة"},
			{"p37", "11eUJNmirInUpzaod6FZq829ko2fTv47c", "service", "مصلحة"},
			{"p38", "11g522pVUxNaXTzssIpo2ED62wOKYdbkG", "légalisation", "مصادقة على الوثائق"},
			{"p39", "11lC3AgqkDH_bYNF80lha7pE54WonsF0R", "projet", "مشروع"},
			{"p40", "11qF2u90RrHP0yyrsnsU6BHFBsntqw5qL", "carte d'identité", "بطاقة التعريف الوطنية"},
			{"p41", "11qQYrmYlFd6iqmdCtGwewDBvURrySBDJ", "carte de priorité", "بطاقة الأولوية"},
			{"p42", "1268brkoRg5aHxu4B-HlE7-B7_arWuTi-", "dossier", "ملف"},
			{"p43", "12MjGxQ7ipAWsHMFxbF48I92YwtbHD79s", "carte de moudjahid", "بطاقة المجاهد"},
			{"p44", "12ArBxatiEkRAby8S8l6H6JWJcYDxlznw", "carte chiffa", "بطاقة الشفاء"},
			{"p45", "12LunLcB4gpJBoun8v1JiLamU8oWIhUlS", "carte grise", "بطاقة رمادية"},
			{"p46", "122_-akmvdU3SRosQkXV9dV_8282tqWo7", "fiche individuelle d'état civil", "بطاقة فردية للحالة المدنية"},
			{"p47", "12NDmjECr73fITcWYpjrhUz0rMrbgTX_E", "carte de vote", "بطاقة الناخب"},
			{"p48", "12NKT5mSjU0CMPq0GG3HZhmt4lHviZW_1", "carte de handicapé", "بطاقة المعوق"},
			{"p49", "12OEEoDBAzR0HN8KPbSugo-CoT3ZgnGnY", "assurance de voiture", "تأمين السيارات"},
			{"p50", "12U5Yg1KXLJPVpOKM-xtHHbwOgQkANz9M", "carte professionnelle", "بطاقة مهنية"},
			{"p51", "12XxoxjSFTXVpmLnfaathEeMwu4XX4Y0c", "carte de groupe sanguin", "بطاقة فصيلة الدم"},
			{"p52", "url", "carte de retraité", "بطاقة المتقاعد"},
			{"p53", "url", "direction", "مديرية"},
			{"p54", "url", "carte d'adhérent", "بطاقة العضوية"},
			{"p55", "url", "autorisation", "تصريح"},
	};
}
