package com.mohamed.barki.asl.lite.resactivity;

import android.app.Activity;
public class ResActivityG extends Activity
{
	public static String[][] resList = new String[][]{
			//الرياضة
			{"g0", "1CMKtcUrEMQ8Cf2dA6UFr7y3cn_sBZfZ1", "lancer du javelot", "رمي الرمح"},
			{"g1", "10Y7bDeKhhKL5-wVaX0P2LhVNf9JvbRuc", "golf", "غولف"},
			{"g2", "1VNE2HKNpi59SI53gy_CqT6EWEmOK6ZzF", "lutte", "مصارعة"},
			{"g3", "1UOlkUurazP-oWcQwnpopuvM6P-AqSVvi", "patinage1", "تزحلق على الجليد1"},
			{"g4", "110bGemNgEWb8IWBTYwWYPNggeGs4q6vC", "tir à l'arc", "رماية بالسهام"},
			{"g5", "1V4t0HkyC49128h-Nab-CKOvChIziRd7z", "lancer du poids", "رمي الجلة"},
			{"g6", "13IKnvfhC2giNMl-k5P_9-6dLViLKhlCx", "haltérophile", "رفع الأثقال"},
			{"g7", "1vBVLAAL_04blXz0jpUKP7AorCK48MqAu", "danse", "رقص"},
			{"g8", "10BT3h0n6zJy-TlwuWXKWZqjAU_GS4taC", "équitation1", "ركوب الخيل1"},
			{"g9", "1di6bvLo-N_FBP1iWbsPMnZIfrcN8iryU", "tennis1", "تنس1"},
			{"g10", "1ZQk3PBTu-B9D3qedNRmAhfplE7gUGOeV", "gymnastique", "جمباز"},
			{"g11", "1OWD3VNqnqTojDUTyCzYzB0VXtY2doeaY", "judo", "جيدو"},
			{"g12", "17hA5eWrrZrn1Y60FRkMzqbNyMPWbGcka", "alpinisme", "تسلق الجبال"},
			{"g13", "1OAcxpt2WSnVZLY5jq2NJIeLpGLIAj-tx", "loisirs", "تسلية"},
			{"g14", "1A6zvYU_ASlJuCQYf9xwzFP61_WecYBDN", "tennis de table", "تنس الطاولة"},
			{"g15", "1izbGgy9_Rl80obzxxDIfxu_-gmZHmYEb", "billard1", "بلياردو1"},
			{"g16", "1IypgA4ihsK9zqmruImov_PLTpvB-UP_H", "bowling", "بولينج"},
			{"g17", "1kaD-fQOBk77yGq6iUEfyGke_KESx_S4S", "ski1", "تزلج1"},
			{"g18", "188mzTprSQaEFbm08aQo-IEQusddnmnz_", "athlétisme", "ألعاب القوى"},
			{"g19", "15553VVwiT2JKH-aDAnjcrFVup4Ae6LSO", "planche à voile", "ألواح شراعية"},
			{"g20", "1bQqF0l7okOWpTMV_Z5FfO-Hg2mJm8Kdl", "olympiade", "أولمبياد"},
			{"g21", "1-gXsnL0tX46EpTyv7WzdIWnLgZ3DkWhI", "water-polo", "كرة الماء"},
			{"g22", "16HCrzliMpGsDqo7ykcUAMfIzdMMMIAig", "handball1", "كرة اليد1"},
			{"g23", "1U4r7uM6M6lfCrML5z4h_2KEhxSfktCfy", "boxe", "ملاكمة"},
			{"g24", "1avK9rfnybZnghAD1x1zjC2aMwRmhVUJl", "basket-ball1", "كرة السلة1"},
			{"g25", "1ALpkxMSirxNq7_QMrq8lPVhpzEZAHPln", "volley-ball", "كرة الطائرة"},
			{"g26", "1Wxgv6sKLAn0Si782cxZWc1LtReT7eLJB", "football1", "كرة القدم1"},
			{"g27", "1MTFMjX9R6kU0moiotP0MVVgKOWSaF6Ue", "karaté1", "كاراتي1"},
			{"g28", "1U8QgNnmrIihar3DIacxTWzeA5aSHvUrY", "goal-ball", "كرة الجرس"},
			{"g29", "1BuVFx0c2C_N3kobP7PICd5X4IRXrcbAb", "pétanque", "كرة حديدية"},
			{"g30", "1gqC_oVx8W7nGi06DOhVrwSEoi47UQhT9", "saut en hauteur", "قفز عالي"},
			{"g31", "1BuAqKPZsDloyaM5l1ZlgRe9QdJE6Aj4G", "saut à la perche", "قفز بالزانة"},
			{"g32", "11LM8vSE_PlCeBgVfVdQZbTuAOs2xv4Nf", "coupe de championnat", "كأس البطولة"},
			{"g33", "1GarE0DYomk2SeKzUfgCrTrR26q0OU6G6", "marathon", "سباق الماراطون"},
			{"g34", "1-CZztNIFyLTsHQKMNNIQk2H5IiWxc2fy", "jeu d'échecs", "شطرنج"},
			{"g35", "1vW3fPI1mIfLp5uWqBKH_Me0wkuW3w9K1", "saut en longueur", "قفز طويل"},
			{"g36", "1rdkemM02oWPuVTPb9Bm7bFSonYfeRf-a", "natation1", "سباحة1"},
			{"g37", "1RCMZVjNn4Re9HirBqmydYfhssdVWueGL", "cyclisme", "سباق الدراجات"},
			{"g38", "1nBdJotbvqBE4KT2dlpZB-yNyoPM9451o", "course automobile", "سباق السيارات"},
			{"g39", "1ai1JSMW43Y-bcw50y7f7osY_8AeT0S9A", "lancer du disque", "رمي القرص"},
			{"g40", "1hMf3RbemLEWV0UrbfEbiSEoJG0jQWXcr", "lancer du marteau", "رمي المطرقة"},
			{"g41", "1ii9pcTg4zCsURFX4mPKFiX5fxZoa-IC8", "sport", "رياضة"},
			{"g42", "url", "badminton", "تنس الريشة"},
			{"g43", "url", "football2", "كرة القدم2"},
			{"g44", "url", "natation2", "سباحة2"},
			{"g45", "url", "tennis2", "تنس2"},
			{"g46", "url", "course", "سباق"},
			{"g47", "url", "rugby", "ريغبي، ريكبي"},
			{"g48", "url", "équitation2", "ركوب الخيل2"},
			{"g49", "url", "basket-ball2", "كرة السلة2"},
			{"g50", "url", "musculation", "كمال الأجسام"},
			{"g51", "url", "karaté2", "كاراتي2"},
			{"g52", "url", "handball2", "كرة اليد2"},
			{"g53", "url", "patinage2", "تزحلق على الجليد2"},
			{"g54", "url", "ski2", "تزلج2"},
			{"g55", "url", "jeux-video", "ألعاب الفيديو"},
			{"g56", "url", "billard2", "بلياردو2"},
			{"g57", "url", "ballon", "كرة"},
			{"g58", "url", "puzzle", "لغز، أحجية"},
			{"g59", "url", "jeux de societé, plateau", "ألعاب الطاولة، اللوحة"},
	};
}
