package com.mohamed.barki.asl.lite.resactivity;

import android.app.Activity;

@SuppressWarnings("SpellCheckingInspection")
public class ResActivityE extends Activity
{
	public static String[][] resList = new String[][]{
			//الولايات
			{"e0", "1ue2MDwob1U9t0dRTVjHxVXR0655wL4gX", "wilayas algériennes", "الولايات الجزائرية"},
			{"e1", "url", "wilaya délégué", "ولاية منتدبة"},
			{"e2", "url", "directeur de wilaya", "مدير ولائي"},
			{"e3", "url", "secrétaire général de wilaya", "أمين عام ولائي"},
			{"e4", "url", "sûreté de wilaya", "أمن ولائي"},
			{"e5", "url", "circonscription administrative", "مقاطعة إدارية"},
			{"e6", "11uFruOEeFsw55LYshcWu5uaQSHfkWugW", "adrar", "أدرار"},
			{"e7", "1ExDSXkpsG_OYofa9gQBun3H51b-eDB4v", "chlef", "الشلف"},
			{"e8", "1a-Yl6iHzfep36eXkVeIsTcYkq7z72TS3", "laghouat", "الأغواط"},
			{"e9", "1pIVS6PYZ0GqzLdU7IGKSKSrk9nid26lP", "oum el bouaghi", "أم البواقي"},
			{"e10", "1fWwrQSblzO56vfMHM8IZLVd4tyBao01_", "batna", "باتنة"},
			{"e11", "1Ft2KzgTsQwv6IfyW_ksClEenLO_zpBMF", "béjaïa", "بجاية"},
			{"e12", "13pK5AlkTWuJPTBwgfgB2P4d6rA5uvSrV", "biskra", "بسكرة"},
			{"e13", "1YRXn50xA15Bl2GvzZEwI3QgXMJST-RYv", "béchar", "بشار"},
			{"e14", "1-mHyPt6E2xE-OygLj0tUyp5fPPKv9hyG", "blida", "البليدة"},
			{"e15", "1yyhxfmG3mTaHXGyBgEHwgFXoHUpcv9gv", "bouira", "البويرة"},
			{"e16", "1oNhD-OBpoc-Wwjiyq8040Ggs6gNx6l5U", "tamanrasset", "تمنراست"},
			{"e17", "1qe0sOw4rtgzfn6lXytBWfXHROjC2s5rH", "tébessa", "تبسة"},
			{"e18", "11a3dAp3iJlC7Nx5NfwwoliilWCY7u6Hy", "tlemcen", "تلمسان"},
			{"e19", "1btkAKTcspDnoldbrYSyFJW4gpu8ZK9Yk", "tiaret", "تيارت"},
			{"e20", "1GT1-Gh2KRlv-TVklTdbmGSTdoYraxxYF", "tizi ouzou", "تيزي وزو"},
			{"e21", "18E9MXIODLccNP5zFc5GJB06MatDogX-7", "alger", "الجزائر العاصمة"},
			{"e22", "1GmntKThAFBPsCRWIOBfyvkbYmTlJD5wD", "djelfa", "الجلفة"},
			{"e23", "1zWvrZ_Pst_BVaC4sd4uT71GxHwzrGxlg", "jijel", "جيجل"},
			{"e24", "1aOGLhAxWiv8KI7Wds6fbS2GMt9VX482b", "sétif", "سطيف"},
			{"e25", "1EqQeoxygurE5xNxb62hT0S76tfiJTY_R", "saïda", "سعيدة"},
			{"e26", "17Adf36fh9mywH8TIO9mEfwQfdbui_Pp5", "skikda", "سكيكدة"},
			{"e27", "19Ta9D9m7ElzL_AWdyuwoGmTz7CdcFlWL", "sidi bel-abbès", "سيدي بلعباس"},
			{"e28", "10g9EMwIQYf6-c23O49ss-b6Sgxrjywbs", "annaba", "عنابة"},
			{"e29", "1mFA5l89dzriay_EyBgScA3CghNbTVYb5", "guelma", "قالمة"},
			{"e30", "1m0uApjkmpqqMw3zgL7xGNPJqxqHAixhR", "constantine", "قسنطينة"},
			{"e31", "1mYikdEGt8i3oBIinI71cn1S70LDSFp9J", "médéa", "المدية"},
			{"e32", "1F2tjiuTzWJITgltkEtDkHuSmDGHC-CoM", "mostaganem", "مستغانم"},
			{"e33", "1Vd6Va7S1tQmVG4BT8qVMujEKE1JRux7z", "m'sila", "المسيلة"},
			{"e34", "14MgAy3z5QvLZKteEf6Jdm2EXtaArtNP4", "mascara", "معسكر"},
			{"e35", "1XDsr7gHSzDWDHNXdHXfqssz4s8AU0ip-", "ouargla", "ورقلة"},
			{"e36", "17bKFDwKUtEkUG3_cDNC2C9tCGujp5xQo", "oran", "وهران"},
			{"e37", "1O6NNtQVAbCv3hI4WwTBM5Ci2pFHfyPZL", "el bayadh", "البيِّض"},
			{"e38", "1tIo_r_QJsPnGc2EOUw-2tdKLFlMUb8ez", "illizi", "إليزي"},
			{"e39", "1bP4qWMLtvBGswG5nQ9TWJ5acv9FMA3C7", "bordj bou arréridj", "برج بوعريريج"},
			{"e40", "1gDYZWAdVkshNpTIvHQk0l2w8gvW-CQzo", "boumerdès", "بومرداس"},
			{"e41", "11ekqLZTqInWg99_br48hccJ2ri4D-0dQ", "el tarf", "الطارف"},
			{"e42", "18t0EkmXIEN-V7Lsa6ADGAFAvL9_ZB1X-", "tindouf", "تندوف"},
			{"e43", "1Tr8iuRbZbzMEaBYkXj4OfxoFmJYvnHXT", "tissemsilt", "تيسمسيلت"},
			{"e44", "1I0U84Z36-TuOMzjXoVSjbwk9S7EfT5lQ", "el oued", "الوادي"},
			{"e45", "1i1z5x-pEyISnPNzlyvcEQvCPEt-Bw-P1", "khenchela", "خنشلة"},
			{"e46", "1l-820J2s3ZjVa21HlbQCFZIhs1CTLyWT", "souk ahras", "سوق أهراس"},
			{"e47", "1nO_VyJ-49SplyqPI10yAbOEEVEi9_OBY", "tipaza", "تيبازة"},
			{"e48", "11LVdIQjZIXPXoRtgO1Zjyt5aYZ6j_HtO", "mila", "ميلة"},
			{"e49", "1FNd8ENdLipw_-eNtouAsT_o2xqvrPRzs", "aïn defla", "عين الدفلى"},
			{"e50", "1gkauvRucJoIm_lQUl7Bb6mdlDN0ANlSn", "naâma", "النعامة"},
			{"e51", "1wo5nNik8SETMaQPuMxelsGiiesMnlS7D", "aïn témouchent", "عين تيموشنت"},
			{"e52", "1nuLnUsSEOsJ3khtP04ieQqcfS6VFO7m8", "ghardaïa", "غرداية"},
			{"e53", "1paxF8Y5sSJoy7btwkH29HR_Lp1ldKRbE", "relizane", "غليزان"},
	};
}
